#!/bin/sh

set -e

path="$HOME/.transformac"

if [ -e $path/.git ]; then
  cd $path && git pull
else
  git clone https://github.com/gekorob/transformac.git $path
fi

ln -sf $path/Brewfile ~/.Brewfile
sh $path/install
