#!/bin/sh

set -e

BASEPATH="$HOME/.transformac"

if [ -e $BASEPATH/.git ]; then
  cd $BASEPATH && git pull
else
  git clone https://github.com/gekorob/transformac.git $BASEPATH
fi

ln -sf $BASEPATH/Brewfile ~/.Brewfile
source $BASEPATH/install

curl https://raw.github.com/gekorob/dotfiles/master/bootstrap -L -o - | sh
curl https://raw.github.com/gekorob/zetashell/master/bootstrap -L -o - | sh
curl https://raw.github.com/gekorob/vinavim/master/bootstrap -L -o - | sh
