#!/bin/sh

set -e

BASEPATH="$HOME/.transformac"

if [ -e $path/.git ]; then
  cd $BASEPATH && git pull
else
  git clone https://github.com/gekorob/transformac.git $BASEPATH
fi

ln -sf $BASEPATH/Brewfile ~/.Brewfile
source $BASEPATH/install
