#!/bin/sh

set -e

sudo softwareupdate -ia

echo 'export PATH=/usr/local/bin:/usr/local/sbin:$PATH' > ~/.profile

source $BASEPATH/osx_general
source $BASEPATH/osx_energy_management
source $BASEPATH/osx_finder_setup
source $BASEPATH/osx_dock_setup
source $BASEPATH/osx_trackpad_mouse_setup

killall Finder || true
killall Dock || true
killall SystemUIServer || true


#brew
export HOMEBREW_ANALYTICS=1

# Download and install Homebrew
if [[ ! -x /usr/local/bin/brew ]]; then
    echo "Info   | Install   | homebrew"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

#xcode
if [ $(xcode-select -p) != "/Applications/Xcode.app/Contents/Developer" ]; then
   echo "cannot find command line tools"
   xcode-select --install
fi
sudo xcodebuild -license accept || true

brew doctor
brew bundle --file="$BASEPATH/Brewfile"
xcrun simctl delete unavailable

#font
wget -N -O ~/Library/Fonts/Inconsolata\ for\ Powerline\ Nerd\ Font\ Complete.otf https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/patched-fonts/Inconsolata/complete/Inconsolata%20for%20Powerline%20Nerd%20Font%20Complete.otf

wget -N -O ~/Library/Fonts/Meslo\ LG\ M\ Regular\ for\ Powerline\ Nerd\ Font\ Complete.otf https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Meslo/M/complete/Meslo%20LG%20M%20Regular%20for%20Powerline%20Nerd%20Font%20Complete.otf

#atom
source $BASEPATH/atom_setup

#ruby
/usr/local/bin/gem install bundler

#vagrant
source $BASEPATH/vagrant_setup

#nvm
sh $BASEPATH/node_setup

#visual studio code
sh $BASEPATH/visual_studio_code_setup

echo pre-pip installation

#powerline
/usr/local/bin/pip3 install pip
/usr/local/bin/pip3 install setuptools
/usr/local/bin/pip3 install psutil
/usr/local/bin/pip3 install powerline-status

#vim
brew install vim --with-override-system-vi

#zsh
brew install zsh
