#!/bin/sh

# Shows Path and Status bar
defaults write com.apple.finder ShowPathbar -bool true
defaults write com.apple.finder ShowStatusBar -bool true

# Show all extensions
defaults write com.apple.finder AppleShowAllFiles -bool false

# Show absolute path on title bar
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Show Library folder
chflags nohidden ~/Library

# Disable the warning on changing extension of a file
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

defaults write com.apple.finder DisableAllAnimations -bool true

# Set new window target
defaults write com.apple.finder NewWindowTarget -string "PfLo"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}"

# Enable selection on QuickLook
defaults write com.apple.finder QLEnableTextSelection -bool true

# Volumes on desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowMountedServersOnDesktop -bool false
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

# Use list view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Use current directory as default search scope in Finder§
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
